### PR TITLE
Bold Text Support 

### PR DESCRIPTION
**Pull request by conorpo**
Went through all the files and added all the stuff needed for bold text, it probably won't work, this is my first time coding in JavaScript or using Github, was just trying to get a feel for GitHub and thought this would be a cool feature for atom-clock.

### CODE REVIEW

**Comment by conorpo** [comment]
Even if this won't get accepted can you guys just look and see If I did it correctly or what I messed up?

**Comment by frasertmay** [comment]
Most of what you've done seems correct however there is a syntax error in `atom-clock.js` [here ](https://github.com/conorpo/atom-clock/blob/d5cfbe14c299669e8ca98c8ec612bedf069f1d39/lib/atom-clock-view.js#L77-L82) which prevents any of the tests from passing.

Your code is this:
```javascript
if(this.showBoldText)
  this.element.appendChild(this.timeElement.bold())
}
else{
  this.element.appendChild(this.timeElement)
}
```
The syntax error is caused by a missing `{` on the first line, it should be this:
```javascript
if(this.showBoldText) {
  this.element.appendChild(this.timeElement.bold())
} else {
  this.element.appendChild(this.timeElement)
}
```

**Comment by conorpo** [comment]
Oh I should've noticed that, however im pretty sure you meant to say `atom-clock-vew.js` as that is where that code is. Another question, is it fine If I do the "bolding" in `atom-clock-view.js` or should I do it where the others seem to have done it in `atom-clock-view-spec.js`?

**Comment by frasertmay** [comment]
I've looked through your code a bit more and it seems you've written a few pieces of code but they aren't 'joined up'. For example you've made an entry in the menu bar but there is no function to respond to it being clicked, and you add the `.atom-clock-bold` class yet there is no style using it so it has no effect.

Also, you seem to be trying to make the text bold in two different ways which are incompatible with each other. Using `.bold()` in `drawElement()` tries to make the text bold with HTML but `.atom-clock-bold` would use CSS/LESS.

I understand you may have made a lot of effort with this feature and it may be your first contribution however I don't think the feature you are proposing would really be needed. Users can make the text bold themselves using their `styles.less` file and the `.atom-clock-time` selector.

**Comment by conorpo** [comment]
Oh okay, well I guess there is no point in trying to fix the issues then, thanks for all the help though. I really appreciate it a lot.

**Comment by b3by** [comment]
Thank you for the effort you put in the request. Happy to help in your first GitHub experience!
As @frasertmay pointed out, the first step before even getting down to the code should be checking whether the feature you're aiming to code isn't there already. In this particular case, the CSS selectors exposed by the class allow you to edit the clock exactly the way you wanted.

Beside the technical issues with the code itself, that @frasertmay already explained, another minor issue would be to conform your code with the style and formatting that is already in place. Also, you can run the specs locally, so obvious mistakes like a missing bracket will be easily spotted.

Hope this helps, and thank you for the PR!

**Comment by frasertmay** [comment]
If you are interested in how you could've made this work, please see my commit [here](https://github.com/frasertmay/atom-clock/commit/e4cd6ca250144f33773ef2a93540cde5e4c4f22f).

I just tidied up your code and added a couple of bits to tie it all together so it now toggles the `.atom-clock-bold` class. Currently there is no style associated with that selector so whilst it does not make the text appear in bold it wouldn't be a difficult task to add that.

The main missing part was not adding a callback for the command triggered by the menu item which is done [like this](https://github.com/frasertmay/atom-clock/commit/e4cd6ca250144f33773ef2a93540cde5e4c4f22f#diff-237cba1a7f21d58ff8119c548c5ae625R28):
```javascript
this.subscriptions.add(atom.commands.add('atom-workspace', {
  'atom-clock:toggle': () => this.toggle(),
  'atom-clock:utc-mode': () => atom.config.set('atom-clock.showUTC', !this.showUTC),
  'atom-clock:boldText': () => atom.config.set('atom-clock.showBoldText', !this.showBoldText)
}))
```
This listens for the command and sets the config value to the opposite of its current value (i.e. toggling it)

The other important part was [setting the bold text class in the `initialize()` function](https://github.com/frasertmay/atom-clock/blob/e4cd6ca250144f33773ef2a93540cde5e4c4f22f/lib/atom-clock-view.js#L22) which is pretty much what you were trying to achieve in `drawElement()` before.

With respect to your question about whether or not to do the "bolding" in `atom-clock-view.js` or `atom-clock-view-spec.js`: the files in the `spec` folder are all tests, they aren't part of the plugin itself, so any functionality would be done in `atom-clock-view.js` and you would test that it works in `atom-clock-view-spec.js`.

If you have any other questions please don't hesitate to ask!

**Comment by conorpo** [comment]
Oh okay, this won't be my last time, I will learn more about javascript and atom and I will add something actually useful to atom-clock, thanks for all the help guys!

**Comment by frasertmay** [comment]
I look forward to it! 👍

**Pull request closed without merging**
