### PR TITLE
Update menu label and update travis.yml

### PR DESCRIPTION
**Pull request by frasertmay**
Changing 'atom-clock' to 'Atom Clock'

screen shot 2017-05-24 at 19 31 01
screen shot 2017-05-24 at 20 10 27

### CODE REVIEW

**Comment by frasertmay** [comment]
The Travis CI build failing doesn't seem to have anything to do with what I changed. According to atom/atom#14440 the Linux beta channel on Travis needs to use the trusty image or none of the builds will succeed

**Comment by b3by** [comment]
Thanks for this. I'll fix the image to trusty, then I'll merge the request. I never noticed the menu label was wrong!

**Comment by frasertmay** [comment]
I just added another commit to the PR changing the image so you can just merge the whole thing if you want?

**Comment by b3by** [comment]
Wow, that's great. Right on spot man, thanks!

**Comment by frasertmay** [comment]
You're welcome, looks like all the checks have passed so it seems to have worked

**Pull request merged**
