### PR TITLE
Revert "Added a README section about customization"

### PR DESCRIPTION
**Pull request by b3by**
Reverts b3by/atom-clock#44

### CODE REVIEW

**Comment by b3by** [comment]
Sorry, I had to revert the PR as I think the last section is missing from the README file, the one related to the UTC tooltip. Could you please add the missing gif? If not, I can rewrite the whole customization section from the scratch, no problem!

**Comment by frasertmay** [comment]
Not sure I follow you, which section was missing?

**Comment by b3by** [comment]
In the last subsection of the customization section, the custom UTC label should be displayed in a gif as well. As in #44, the "Customization with UTC" subsection does not have gif (and the last full stop is missing). Nothing serious anyway, I can fix the README file (I also want to add more stuff to it, I'll do it right now). Sorry about this!

**Comment by frasertmay** [comment]
Weird, it looked like there was a gif to me, or do you mean one showing it being used with the tooltip as well?

screen shot 2017-08-30 at 17 49 51

screen shot 2017-08-30 at 17 54 36

**Comment by b3by** [comment]
Yes, correct, a gif with the tooltip as well.

**Comment by frasertmay** [comment]
Oh okay, here's a snippet and a gif for you to use so they all match up

```scss
.atom-clock-tooltip.atom-clock-utc .tooltip-inner {
  color: white;

  &:before {
    content: "UTC Time: "
  }
}
```

utc_tooltip

**Pull request merged**
