### PR TITLE
Add tooltip to show a longer format on hover

### PR DESCRIPTION
**Pull request by mehcode**

### CODE REVIEW

**Comment by b3by** [comment]
I like the idea of a tooltip quite much, thank you!
For what it concerns the PR, there are a couple of things missing. There should be a subscription for any change in the settings to the tooltip date format. Also, specs are to be written for the tooltip.
The last small detail is, the tooltip dispose line in the destroy method should not have the semicolon at the end (I'm trying to keep the whole code consistent style-wise).

If you cannot take care of these things, I will just merge the PR and fix them myself.

Cheers!

**Comment by b3by** [comment]
I am still leaving this behind for this release (0.1.8) as I am still lot sure if I want the feature in the package. Also, specs still need to be written, and I don't have time right now.
I will probably integrate this feature with an extra flag in the configuration to enable/disable the tooltip, defined as opt-in option.

**Comment by frasertmay** [comment]
If you're interested I have a branch [here](https://github.com/frasertmay/atom-clock/tree/tooltip) with an opt-in tooltip with specs written you can have a look at if you want. If you like it I can submit a pull request?

screen shot 2017-05-26 at 12 48 45
screen shot 2017-05-26 at 12 49 03

**Comment by b3by** [comment]
Wow, that's rad. I gave a look at your branch, everything seems to be in place. If you submit the PR, I will wait few days anyway before accepting it anyway, as I'd like to see if the release from yesterday night gives any sort of problem. Also, I'll look at it more closely, as I'm buried with work atm!
Thanks a lot!

**Comment by frasertmay** [comment]
Thanks! I'll submit the PR

**Comment by b3by** [comment]
This one was closed in#29.

**Pull request closed without merging**
